var fs = require('fs');

var html = fs.readFileSync('index.html','utf8');

// convert to something that should work in a .h file
var escaped = html.replace(/\\/g,'\\\\').replace(/\"/g,'\\"').replace(/[\n\t]/g,'');

var hFile = `/*

NOTE: don't edit manually, this is generated by build.sh

*/

const char* HTMLPAGE="${escaped}";`

fs.writeFileSync('HTMLPAGE.h',hFile);
